name: Format and Lint

env:
  TURBO_TELEMETRY_DISABLED: 1

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  checks:
    name: Run Checks
    runs-on: ubuntu-24.04
    permissions:
      contents: read

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@fe104658747b27e96e4f7e80cd0a94068e53901d # v2.16.1
        with:
          egress-policy: audit

      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 2 # Recommended by turbo team

      - name: Setup Environment
        uses: ./.github/actions/setup
        with:
          skip-compact: "true"

      - name: Format & Lint
        run: turbo fmt-and-lint:ci
